
export const metadata = {
  title: 'Ecpenditcher | Login/Register',
  description: 'Generated by create next app',
};

const Login = () => {
  return (
    <div className='flex items-center justify-center w-full min-h-[calc(100vh-10rem)]'>
      <div className='flex flex-col w-full h-full space-y-3 bg-white border shadow-xl lg:p-5 lg:w-1/2 rounded-2xl'>
        <h2 className='text-2xl font-light tracking-wider text-center underline underline-offset-4 text-slate-700'>
          Expenditcher
        </h2>
        <p className='text-sm text-center text-slate-600' data-test-id='asd'>
          Easily sign-in or register with one of your accounts. Signing in or
          registering with any of the below accounts will avoid another hassled
          to remember usernames and passwords!
        </p>
        <h4 className='py-4 font-semibold tracking-wide text-center text-slate-500 underline-offset-2'>
          Login or register using
        </h4>
        <div className='flex justify-center w-full'>
          <button className='inline-flex items-center justify-center w-3/4 h-full gap-2 py-2 font-medium tracking-wider border rounded-lg shadow-sm text-slate-600 hover:text-slate-900'>
            1. Google Account
          </button>
        </div>
        <div className='flex justify-center w-full'>
          <button className='w-3/4 h-full py-2 font-medium tracking-wider border rounded-lg shadow-sm text-slate-600 hover:text-slate-900'>
            2. Github Account
          </button>
        </div>
      </div>
    </div>
  );
}


/*


*/
export default Login