import React from 'react'
import AddExpenseForm from '@/components/AddExpenseForm';


export const metadata = {
  title: 'Ecpenditcher | Add Expense',
  description: 'Generated by create next app',
};

const AddExpense = (params) => {
  return (
    <div className='w-full h-[calc(100vh-4rem)] flex justify-center items-center p-1 bg-slate-100'>
      <AddExpenseForm/>
    </div>
  );
}

export default AddExpense