import { Mulish, Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: 'Ecpenditcher | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} container mx-auto h-screen select-none px-4 lg:px-8 flex flex-col bg-white lg:py-2 gap-2 text-pretty`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
