import Featured from '@/components/Featured';
import React from 'react'

export const metadata = {
  title: 'Ecpenditcher | Dashboard',
  description: 'Generated by create next app',
};

const Dashboard = () => {
  return (
    <div className='w-full min-h-[calc(100vh-4rem)] overflow-y-auto'>
      <Featured />
    </div>
  );
}

export default Dashboard