import React from 'react'

export const metadata = {
  title: 'Ecpenditcher | Dashboard',
  description: 'Generated by create next app',
};

const Dashboard = () => {
  return (
    <div className='w-full min-h-[calc(100vh-10rem)] border overflow-y-auto'>
     <p>Featured</p>
    
    </div>
  )
}

export default Dashboard